"""
Export service — PDF and CSV reports.
"""
import io, csv
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
from models.schemas import SessionData


def generate_pdf(session: SessionData) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm, leftMargin=15*mm, rightMargin=15*mm)
    styles = getSampleStyleSheet()
    title_s = ParagraphStyle('T', parent=styles['Title'], fontSize=22, textColor=colors.HexColor('#4f46e5'), spaceAfter=6)
    sub_s = ParagraphStyle('S', parent=styles['Normal'], fontSize=10, textColor=colors.HexColor('#64748b'), spaceAfter=16)
    h_s = ParagraphStyle('H', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#1e293b'), spaceBefore=12, spaceAfter=8)
    b_s = ParagraphStyle('B', parent=styles['Normal'], fontSize=9, textColor=colors.HexColor('#475569'), spaceAfter=4)

    el = []
    el.append(Paragraph("Tech Vista", title_s))
    el.append(Paragraph(f"Bias-Aware AI Resume Screening Report | {datetime.now().strftime('%Y-%m-%d %H:%M')}", sub_s))
    el.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#4f46e5')))
    el.append(Spacer(1, 12))

    jd_title = session.jd.title if session.jd else "N/A"
    el.append(Paragraph("Session Summary", h_s))
    el.append(Paragraph(f"Job Description: {jd_title}", b_s))
    el.append(Paragraph(f"Candidates Screened: {len(session.scores)}", b_s))
    el.append(Paragraph(f"Weights: Skills {session.weights.skills*100:.0f}% | Exp {session.weights.experience*100:.0f}% | Edu {session.weights.education*100:.0f}%", b_s))
    el.append(Spacer(1, 12))

    el.append(Paragraph("Candidate Rankings", h_s))
    td = [["Rank","Candidate","Skills","Exp.","Edu.","Composite","Status"]]
    for s in sorted(session.scores, key=lambda x: x.composite_score, reverse=True):
        td.append([str(s.rank), s.candidate_name[:25], f"{s.skills_score:.0f}%", f"{s.experience_score:.0f}%", f"{s.education_score:.0f}%", f"{s.composite_score:.0f}%", "Adjusted" if s.adjusted else "Clear"])
    t = Table(td, colWidths=[30,120,50,50,50,70,55])
    t.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),colors.HexColor('#4f46e5')),('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('FONTSIZE',(0,0),(-1,0),9),('FONTSIZE',(0,1),(-1,-1),8),
        ('TEXTCOLOR',(0,1),(-1,-1),colors.HexColor('#1e293b')),('ALIGN',(0,0),(-1,-1),'CENTER'),
        ('ALIGN',(1,1),(1,-1),'LEFT'),
        ('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.HexColor('#f8fafc'),colors.white]),
        ('GRID',(0,0),(-1,-1),0.5,colors.HexColor('#e2e8f0')),
        ('TOPPADDING',(0,0),(-1,-1),4),('BOTTOMPADDING',(0,0),(-1,-1),4),
    ]))
    el.append(t)
    el.append(Spacer(1, 16))

    el.append(Paragraph("Top Candidate Details", h_s))
    for s in sorted(session.scores, key=lambda x: x.composite_score, reverse=True)[:10]:
        el.append(Paragraph(f"<b>#{s.rank} — {s.candidate_name}</b> (Composite: {s.composite_score:.0f}%)", ParagraphStyle('CN', parent=b_s, fontSize=10, textColor=colors.HexColor('#1e293b'))))
        el.append(Paragraph(f"Skills: {s.skills_explanation}", b_s))
        el.append(Paragraph(f"Experience: {s.experience_explanation}", b_s))
        el.append(Paragraph(f"Education: {s.education_explanation}", b_s))
        el.append(Spacer(1, 8))

    if session.bias_audit:
        el.append(Paragraph("Bias Audit Report", h_s))
        el.append(Paragraph(f"Status: {session.bias_audit.overall_status} | Tests: {session.bias_audit.tests_run} | Flags: {session.bias_audit.flags_detected}", b_s))
        for cat, detail in session.bias_audit.details.items():
            flag = "FLAGGED" if detail.get("bias_detected") else "Pass"
            el.append(Paragraph(f"{cat.replace('_',' ').title()} ({detail.get('test_used','')}): p={detail.get('p_value',0):.4f} | d={detail.get('effect_size',0):.4f} | {flag}", b_s))

    el.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#94a3b8')))
    el.append(Paragraph("Generated by Tech Vista. No raw resume text or PII beyond names.", ParagraphStyle('F', parent=b_s, fontSize=7, textColor=colors.HexColor('#94a3b8'))))
    doc.build(el)
    return buf.getvalue()


def generate_csv(session: SessionData) -> str:
    out = io.StringIO()
    w = csv.writer(out)
    w.writerow(["Rank","Candidate","Skills","Exp","Edu","Composite","Normalized","Tier","Years","Cohort","Bias","Skills Explanation","Exp Explanation","Edu Explanation"])
    for s in sorted(session.scores, key=lambda x: x.composite_score, reverse=True):
        w.writerow([s.rank, s.candidate_name, f"{s.skills_score:.2f}", f"{s.experience_score:.2f}", f"{s.education_score:.2f}", f"{s.composite_score:.2f}",
            f"{s.normalized_score:.2f}" if s.normalized_score is not None else "N/A",
            s.institution_tier, s.experience_years, s.experience_cohort, "Adjusted" if s.adjusted else "Clear",
            s.skills_explanation, s.experience_explanation, s.education_explanation])
    if session.bias_audit:
        w.writerow([])
        w.writerow(["BIAS AUDIT"])
        for cat, d in session.bias_audit.details.items():
            w.writerow([cat.replace("_"," ").title(), d.get("test_used",""), f"p={d.get('p_value',0):.4f}", f"d={d.get('effect_size',0):.4f}", "Flagged" if d.get("bias_detected") else "Pass"])
    return out.getvalue()
